title: Pedro Pontes García
description: Computer Science and Mathematics student at Cornell University
show_downloads: true
github_url: "https://github.com/pedropontesgarcia"
google_analytics:
theme: jekyll-theme-cayman